api/urls.py
from django.urls import path, include
from .views import ProductoList, ProductoDetalle

urlpatterns = [
    path('v1/productos/',ProductoList.as_view(),name='producto_list'),
    path('v1/productos/<str:codigo>',ProductoDetalle.as_view(),name='producto_detalle'),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/',include(('inv.urls', 'inv'), namespace='inv')),
    path('cmp/',include(('cmp.urls', 'cmp'), namespace='cmp')),
    path('fac/',include(('fac.urls', 'fac'), namespace='fac')),
    path('api/',include(('api.urls', 'api'), namespace='api')),
    
    path('admin/', admin.site.urls),
]

fac/urls.py
from django.urls import path, include

from .views import ClienteView, ClienteNew, ClienteEdit, clienteInactivar, \
    FacturaView, facturas, \
    ProductoView, \
    borrar_detalle_factura

from .reportes import imprimir_factura_recibo, imprimir_factura_list

urlpatterns = [
    
    path('clientes/',ClienteView.as_view(), name='cliente_list'),
    path('clientes/new',ClienteNew.as_view(), name='cliente_new'),
    path('clientes/<int:pk>',ClienteEdit.as_view(), name='cliente_edit'),
    path('clientes/estado/<int:id>',clienteInactivar, name='cliente_inactivar'),

    path('facturas/',FacturaView.as_view(), name='factura_list'),
    path('facturas/new',facturas, name='factura_new'),
    path('facturas/edit/<int:id>',facturas, name="factura_edit"),

    path('facturas/buscar-producto',ProductoView.as_view(), name='factura_producto'),
    
    path('facturas/borrar-detalle/<int:id>',borrar_detalle_factura, name='factura_borrar_detalle'),

    path('facturas/imprimir/<int:id>',imprimir_factura_recibo, name="factura_imprimir_one"),

    path('facturas/imprimir-todas/<str:f1>/<str:f2>',imprimir_factura_list, name="factura_imprimir_all"),
]

inv/urls.py
from django.urls import path

from .views import CategoriaView, CategoriaNew, CategoriaEdit,  \
    CategoriaDel, \
    SubCategoriaView, SubCategoriaNew, SubCategoriaEdit, SubCategoriaDel, \
    MarcaView, MarcaNew, MarcaEdit, marca_inactivar, \
    UMView, UMNew, UMEdit, um_inactivar, \
    ProductoView, ProductoNew, ProductoEdit, producto_inactivar

urlpatterns = [
    path('categorias/',CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new',CategoriaNew.as_view(), name='categoria_new'),
    path('categorias/edit/<int:pk>',CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/delete/<int:pk>',CategoriaDel.as_view(), name='categoria_del'),

    path('subcategorias/',SubCategoriaView.as_view(), name='subcategoria_list'),
    path('subcategorias/new',SubCategoriaNew.as_view(), name='subcategoria_new'),
    path('subcategorias/edit/<int:pk>',SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path('subcategorias/delete/<int:pk>',SubCategoriaDel.as_view(), name='subcategoria_del'),

    path('marcas/',MarcaView.as_view(), name='marca_list'),
    path('marcas/new',MarcaNew.as_view(), name='marca_new'),
    path('marcas/edit/<int:pk>',MarcaEdit.as_view(), name='marca_edit'),
    path('marcas/inactivar/<int:id>',marca_inactivar, name='marca_inactivar'),

    path('um/',UMView.as_view(), name="um_list"),
    path('um/new',UMNew.as_view(), name="um_new"),
    path('um/edit/<int:pk>',UMEdit.as_view(), name="um_edit"),
    path('um/inactivar/<int:id>',um_inactivar, name="um_inactivar"),

    path('productos/',ProductoView.as_view(), name="producto_list"),
    path('productos/new',ProductoNew.as_view(), name="producto_new"),
    path('productos/edit/<int:pk>',ProductoEdit.as_view(), name="producto_edit"),
    path('productos/inactivar/<int:id>',producto_inactivar, name="producto_inactivar"),
]

fac/models.py
from django.db import models

#para los signals
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.db.models import Sum

from bases.models import ClassModel, ClassModel2
from inv.models import Producto
# Create your models here.

class Cliente(ClassModel):
    NAT='Natural'
    JUR= 'Jurídica'
    TIPO_CLIENTE = [
        (NAT, 'Natural'),
        (JUR, 'Jurídica')
    ]
    nombres = models.CharField(
        max_length=100
    )
    apellidos = models.CharField(
        max_length=100
    )
    direccion=models.CharField(
        max_length=100,
        null=True
    )
    telefono = models.CharField(
        max_length=20,
        null=True,
        blank=True
    )
    tipo=models.CharField(
        max_length=10,
        choices=TIPO_CLIENTE,
        default=NAT
    )
    email= models.CharField(
        max_length=100,
        unique=True
    )
    identificacion = models.CharField(
        max_length=13,
        unique=True
    )
    

    def __str__(self):
        return'{} {}'.format(self.apellidos,self.nombres)
    
    def save(self):
        self.nombres=self.nombres.upper()
        self.apellidos=self.apellidos.upper()
        self.direccion=self.direccion.upper()
        super(Cliente, self).save()

    class Meta:
        verbose_name_plural = 'Clientes'

class FacturaEnc(ClassModel2):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    sub_total=models.FloatField(default=0)
    descuento=models.FloatField(default=0)
    total=models.FloatField(default=0)
    subtotal_iva=models.FloatField(default=0)
    total_iva=models.FloatField(default=0)

    def __str__(self):
        return '{}'.format(self.id)

    def save(self):
        self.total = self.sub_total - self.descuento
        self.subtotal_iva=float(self.total * 0.12)
        self.total_iva=self.total + self.subtotal_iva
        super(FacturaEnc,self).save()

    class Meta:
        verbose_name_plural = "Encabezado Facturas"
        verbose_name="Encabezado Factura"
        permissions = [
            ('sup_caja_facturaenc', 'Permisos de Supervisor de Caja Encabezado')
        ]
    

class FacturaDet(ClassModel2):
    factura = models.ForeignKey(FacturaEnc,on_delete=models.CASCADE)
    producto=models.ForeignKey(Producto,on_delete=models.CASCADE)
    cantidad=models.BigIntegerField(default=0)
    precio=models.FloatField(default=0)
    sub_total=models.FloatField(default=0)
    descuento=models.FloatField(default=0)
    total=models.FloatField(default=0)
    subtotal_iva=models.FloatField(default=0)
    total_iva=models.FloatField(default=0)

    def __str__(self):
        return '{}'.format(self.producto)

    def save(self):
        self.sub_total = float(float(int(self.cantidad)) * float(self.precio))
        self.total = self.sub_total - float(self.descuento)
        self.subtotal_iva=float(self.total * 0.12)
        self.total_iva=self.total + self.subtotal_iva
        super(FacturaDet, self).save()
    
    class Meta:
        verbose_name_plural = "Detalles Facturas"
        verbose_name="Detalle Factura"
        permissions = [
            ('sup_caja_facturadet', 'Permisos de Supervisor de Caja Detalle')
        ]

@receiver(post_save, sender=FacturaDet)
def detalle_fac_guardar(sender,instance, **kwargs):
    factura_id = instance.factura.id
    producto_id = instance.producto.id

    enc = FacturaEnc.objects.get(pk=factura_id)
    if enc:
        sub_total = FacturaDet.objects \
            .filter(factura=factura_id) \
            .aggregate(sub_total=Sum('sub_total')) \
            .get('sub_total', 0.00)

        descuento = FacturaDet.objects \
            .filter(factura=factura_id) \
            .aggregate(descuento=Sum('descuento')) \
            .get('descuento', 0.00)

        enc.sub_total = sub_total
        enc.descuento = descuento
        enc.save()

        prod=Producto.objects.filter(pk=producto_id).first()
        if prod:
            cantidad = int(prod.existencia) - int(instance.cantidad)
            prod.existencia = cantidad
            prod.save()

fac/forms.py
from django import forms

from .models import Cliente

class ClienteForm(forms.ModelForm):
    class Meta:
        model=Cliente
        fields=['nombres','apellidos','tipo', 'telefono', 'email', 'identificacion', 'direccion', 'estado']
        exclude=['um','fm', 'uc', 'fc']
        widget={'descripcion': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

    def clean(self):
        try:
            sc = Cliente.objects.get(
                email=self.cleaned_data["email"]
            )

            if not self.instance.pk:
                print("Registro ya existe")
                raise forms.ValidationError("Registro Ya Existe")
            elif self.instance.pk!=sc.pk:
                print("Cambio no permitido")
                raise forms.ValidationError("Cambio No Permitido")
        except Cliente.DoesNotExist:
            pass
        return self.cleaned_data

fac/views.py
from django.shortcuts import render, redirect
from django.views import generic

from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse, JsonResponse
from datetime import datetime
from django.contrib import messages

from django.contrib.auth import authenticate

from bases.views import SinPrivilegios, VistaBaseCreate, VistaBaseEdit
from .models import Cliente, FacturaDet, FacturaEnc
from .forms import ClienteForm
import inv.views as inv 
from inv.models import Producto

class ClienteView(SinPrivilegios, generic.ListView):
    model = Cliente
    template_name = 'fac/cliente_list.html'
    context_object_name = 'obj'
    permission_required = 'fac.view_cliente'



class ClienteNew(VistaBaseCreate):
    model=Cliente
    template_name='fac/cliente_form.html'
    form_class=ClienteForm
    success_url=reverse_lazy('fac:cliente_list')
    permission_required='fac.add_cliente'

    def get(self, request, *args, **kwargs):        
        try:
            t = request.GET["t"]
        except:
            t = None
        
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form':form, 't':t})

class ClienteEdit(VistaBaseEdit):
    model=Cliente
    template_name='fac/cliente_form.html'
    form_class=ClienteForm
    success_url=reverse_lazy('fac:cliente_list')
    permission_required='fac.change_cliente'

    def get(self, request, *args, **kwargs):
        try:
            t = request.GET["t"]
        except:
            t = None
        
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        context = self.get_context_data(object=self.object, form=form, t=t)
        return self.render_to_response(context)

@login_required(login_url='/login/')
@permission_required('fac.change_cliente', login_url='/login/')
def clienteInactivar(request, id):
    cliente = Cliente.objects.filter(pk=id).first()

    if request.method=='POST':
        if cliente:
            cliente.estado = not cliente.estado
            cliente.save()
            return HttpResponse('OK')
        return HttpResponse('FAIL')
    
    return HttpResponse('FAIL')

class FacturaView(SinPrivilegios, generic.ListView):
    model=FacturaEnc
    template_name = 'fac/factura_list.html'
    context_object_name = 'obj'
    permission_required = 'fac.view_facturaenc'

    def get_queryset(self):
        user = self.request.user
        qs = super().get_queryset()
        
        if not user.is_superuser:
            qs=qs.filter(uc=user)

        return qs

@login_required(login_url='/login/')
@permission_required('fac.change_facturaenc', login_url='bases:sin_privilegios')
def facturas(request,id=None):
    template_name = 'fac/facturas.html'

    detalle={}
    clientes = Cliente.objects.filter(estado=True)

    if request.method == "GET":
        enc = FacturaEnc.objects.filter(pk=id).first()
        if id:
            if not enc:
                messages.error(request,'Factura No Existe')
                return redirect("fac:factura_list")

            usr = request.user
            if not usr.is_superuser:
                if enc.uc != usr:
                    messages.error(request,'Factura no fue creada por usuario')
                    return redirect("fac:factura_list")
        if not  enc:
            encabezado = {
                'id':0,
                'fecha':datetime.today(),
                'cliente':0,
                'sub_total':0.00,
                'descuento':0.00,
                'total':0.00,
                'subtotal_iva':0.00,
                'total_iva':0.00
            }
            detalle=None
        else:
            encabezado = {
                'id':enc.id,
                'fecha': enc.fecha,
                'cliente':enc.cliente,
                'sub_total':enc.sub_total,
                'descuento':enc.descuento,
                'total':enc.total,
                'subtotal_iva':enc.subtotal_iva,
                'total_iva':enc.total_iva
            }
        detalle=FacturaDet.objects.filter(factura=enc)
        contexto = {"enc":encabezado,"det":detalle,"clientes":clientes}  
        return render(request,template_name,contexto)

    if request.method == "POST":
        cliente = request.POST.get("enc_cliente")
        fecha  = request.POST.get("fecha")
        cli=Cliente.objects.get(pk=cliente)

        if not id:
            enc = FacturaEnc(
                cliente = cli,
                fecha = fecha
            )
            if enc:
                enc.save()
                id = enc.id
        else:
            enc = FacturaEnc.objects.filter(pk=id).first()
            if enc:
                enc.cliente = cli
                enc.save()

        if not id:
            messages.error(request,'No Puedo Continuar No Pude Detectar No. de Factura')
            return redirect("fac:factura_list")

        codigo = request.POST.get("codigo")
        cantidad = request.POST.get("cantidad")
        precio = request.POST.get("precio")
        s_total = request.POST.get("sub_total_detalle")
        descuento = request.POST.get("descuento_detalle")
        total = request.POST.get("total_sub")

        prod = Producto.objects.get(codigo=codigo)
        det = FacturaDet(
            factura = enc,
            producto = prod,
            cantidad = cantidad,
            precio = precio,
            sub_total = s_total,
            descuento = descuento,
            total = total
        )
        
        if det:
            det.save()
        
        return redirect("fac:factura_edit",id=id)
         
    return render(request, template_name, contexto)

class ProductoView(inv.ProductoView):
    template_name='fac/buscar_producto.html'

def borrar_detalle_factura(request, id):
    template_name = "fac/factura_borrar_detalle.html"

    det = FacturaDet.objects.get(pk=id)

    if request.method=="GET":
        context={"det":det}

    if request.method == "POST":
        usr = request.POST.get("usuario")
        pas = request.POST.get("pass")

        user =authenticate(username=usr,password=pas)

        if not user:
            return HttpResponse("Usuario o Clave Incorrecta")
        
        if not user.is_active:
            return HttpResponse("Usuario Inactivo")

        if user.is_superuser or user.has_perm("fac.sup_caja_facturadet"):
            det.id = None
            det.cantidad = (-1 * det.cantidad)
            det.sub_total = (-1 * det.sub_total)
            det.descuento = (-1 * det.descuento)
            det.total = (-1 * det.total)
            det.save()

            return HttpResponse("ok")

        return HttpResponse("Usuario no autorizado")
    
    return render(request,template_name,context)

fac/templates/fac/cliente_form.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        {% if obj %}
        <form method="POST" id="frmCliente" role="form" class="form-inline" action="{% url 'fac:cliente_edit' obj.pk %}">
        {% else %}
        <form method="POST" id="frmCliente" role="form" class="form-inline" action="{% url 'fac:cliente_new' %}">
        {% endif %}
            <div class="col-xl-12 col-md-12 mb-12">
                {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                    {% if obj %} Editar {% else %} Nuevo {% endif %} Cliente
                                    {% if t %} En Factura {% endif %}
                                </div>
                                <div class="dropdown-divider"></div>
                                {% csrf_token %}
                                <div class="row">
                                    {{ form.as_p}}
                                </div>
                                <div class="dropdown-divider"></div>
                                <div class="row">
                                    <div class="col">
                                        <button type="submit" class="btn btn-success"><span class="fa fa-save"></span> Guardar</button>
                                        <!-- <a href="{% url 'inv:um_list' %}" class="btn btn-danger"><span class="fa fa-undo"> Cancelar</span></a> -->
                                        <button type="button" class="btn btn-danger" onclick="return cerrar_modal()">
                                            <span class="fa fa-undo"></span> Cancelar
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- <div class="col-auto">
                            <i class="far fa-calendar-plus fa-2x text-gray-300 mt-4"></i>
                        </div> -->
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% if t %}
<script>
$("#frmCliente").submit(function( e ) {
    var frm = $('#frmCliente');
    $.ajax({
            type: frm.attr('method'),
            url: frm.attr('action'),
            data: frm.serialize(),
            success: function (data) {
                // alert(data);
                window.location.reload(true);
            },
            error: function(data) {
                alert(data);
            }
        });
        return false;
});

</script>
{% endif %}

fac/templates/fac/cliente_list.html
  
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Listado de Clientes</h6>
    <div class="dropdown no-arrow">
      <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
        <div class="dropdown-header">Acciones:</div>
        
      </div>
    </div>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    {% if not obj %}
    <div class="alert alert-info">No hay Clientes</div>
    {% endif %}
    <div class="buttons-toolbar">
      <a class="dropdown-item" onclick="return abrir_modal('{% url 'fac:cliente_new' %}')" href="#"><i class="far fa-calendar-plus"></i> Nuevo</a>
    </div>
    <table 
      id="table" 
      data-toggle="table" 
      data-pagination="true" 
      data-search="true" 
      data-show-columns="true" 
      data-show-toggle="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-EC"
    
    >
      <thead>        
        <th data-sortable="true" data-field="nombres">Nombres</th>
        <th data-sortable="true" data-field="apellidos">Apellidos</th>
        <th data-sortable="true" data-field="tipo">Tipo</th>
        <th data-field="telefono">Teléfono</th>
        <th data-field="email">Email</th>
        <th data-field="identificacion">Identificación</th>
        <th data-field="direccion">Dirección</th>
        <th data-field="estado">Estado</th>
        <th class="all">Acciones</th>
      </thead>
      <tbody>
        {% for item in obj%}
        <tr>
          <td>{{ item.nombres }}</td>
          <td>{{ item.apellidos }}</td>
          <td>{{ item.tipo }}</td>
          <td>{{ item.telefono }}</td>
          <td>{{ item.email }}</td>
          <td>{{ item.identificacion }}</td>
          <td>{{ item.direccion }}</td>
          <td >{# item.estado|yesno:'Activo,Inactivo' #}
            <div onclick="inactivar({{ item.id }})">
              {% if item.estado %}
                <i class="far fa-thumbs-up text-primary"></i>
              {% else %}
                <i class="far fa-thumbs-down text-danger"></i>
              {% endif %}
            </div>
            
          </td>
          <td>
            <button class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'fac:cliente_edit' item.id %}')">
                <i class="far fa-edit"></i>
            </button>

          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}
{% block js_page %}
<script>
  function inactivar(id)
  {
    var data = {id:id};
    data = JSON.stringify(data);
    var token = '{{csrf_token}}';
    $.ajax({
      headers : {'X-CSRFToken': token},
      type:'POST',
      url: '/fac/clientes/estado/'+id,
      success: function(response){
        if(response==='OK'){
          location.reload(true);
        } else {
          mensaje('Error intentando Cambiar Estado a Cliente')
        }
      },
      error: function(jqXHR, textStatus, errorThrow){
        console.log(textStatus, errorThrow);
        mensaje(errorThrow, 'red');
        cerrar_modal();
      }
    });
  }
  // Call the dataTables jQuery plugin
  // $(document).ready(function() {
  //   $('.table').DataTable({
  //     "language": {
  //       "sProcessing": "Procesando...",
  //       "sLengthMenu": "Mostrar _MENU_ registros",
  //       "sZeroRecords": "No se encontraron resultados",
  //       "sEmptyTable": "Ningún dato disponible en esta tabla",
  //       "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
  //       "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
  //       "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
  //       "sInfoPostFix": "",
  //       "sSearch": "Buscar:",
  //       "sUrl": "",
  //       "sInfoThousands": ",",
  //       "sLoadingRecords": "Cargando...",
  //       "oPaginate": {
  //           "sFirst": "<span class='fa fa-angle-double-left'></span>",
  //           "sLast": "<span class='fa fa-angle-double-right'></span>",
  //           "sNext": "<span class='fa fa-angle-right'></span>",
  //           "sPrevious": "<span class='fa fa-angle-left'></span>"
  //       },
  //       "oAria": {
  //           "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
  //           "sSortDescending": ": Activar para ordenar la columna de manera descendente"
  //       }
  //     }
  //   });
  // });
  </script>
{% endblock %}

fac/templates/fac/factura_borrar_detalle.html
<label class="text-danger">¿Anular Producto <b>{{det.producto.descripcion}}</b> de factura <b>{{det.factura.id}}</b>?</label>
<div>
    <div class="form-group">
        <label class="control-label">Usuario</label>
        <input type="text" id="usuario" class="form-control" required>
    </div>
    <div class="form-group">
        <label class="control-label">Contraseña</label>
        <input type="password" id="password" class="form-control" required>
    </div>
</div>

fac/templates/fac/factura_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Listado de Facturas</h6>
    <!-- <div class="dropdown no-arrow">
      <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
        <div class="dropdown-header">Acciones:</div>
        <a class="dropdown-item" onclick="return abrir_modal('{% url 'fac:cliente_new' %}')" href="#"><i class="far fa-calendar-plus"></i> Nuevo</a>
      </div>
    </div> -->
  </div>
  <!-- Card Body -->
  <div class="card-body">
    <div class="row">
      <div class="col-md-4">
        <input type="text" class="form-class" name="f1" id="f1" readonly>
      </div>
      <div class="col-md-4">
        <input type="text" class="form-class" name="f2" id="f2" readonly>
      </div>
      <div class="col-md-4">
        <button class="btn btn-warning" type="button" id="btnPrint">Imprimir</button>
      </div>
    </div>
    <hr>

    
    {% if not obj %}
    <div class="alert alert-info">No Hay Facturas</div>
    {% endif %}
    <div class="buttons-toolbar">
        <a class="btn btn-success" href="{% url 'fac:factura_new' %}"><i cass="far fa-calendar-plus"></i> Nuevo</a>
    </div>

    <table 
      id="table"
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-show-columns="true"
      data-show-toggle="true"
      data-show-fullscreen="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-NI"
    >
    <thead>
      <th data-sortable="true" data-field="id">No.</th>        
      <th data-sortable="true" data-field="nombres">Cliente</th>
      <th data-sortable="true" data-field="apellidos">Total</th>
      <th data-field="estado">Estado</th>
      <th class="all">Acciones</th>
    </thead>
    <tbody>
      {% for item in obj%}
      <tr>
        <td>{{ item.id }}</td>
        <td>{{ item.cliente }}</td>
        <td>{{ item.total_iva }}</td>
        <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
        <td>
          <a href="{% url 'fac:factura_edit' item.id %}" class="href btn btn-warning btn-circle">
              <i class="far fa-edit"></i>
          </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>


    </table>
  </div>
</div>
{% endblock %}
{% block js_page %}
<script>
$(function(){
  $("#f1, #f2").datetimepicker({
      format: 'Y-m-d',
      timepicker:false
  });

  $("#btnPrint").click(function(e){
    e.preventDefault();
    var f1,f2;
    f1 = $("#f1").val();
    f2 = $("#f2").val();
    if(f1=="" || f1==null){
      f1="2019-06-01";
    }
    if(f2=="" || f2==null){
      var d = new Date();
      var f2 = d.getFullYear() + "-" + (d.getMonth()+1) + "-" + d.getDate();
    }
    
    var url = "imprimir-todas/" + f1 + "/" + f2;

    window.open(url,'facturas');
    
  });
});
</script>
{% endblock %}

fac/templates/fac/factura_print_all.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Listado de Compras</title>

    <style type="text/css">
    @page {
        size: letter;
        margin: 1cm;
    }
    .table {
        width: 100%;
        max-width: 100%;
        margin-bottom: 5px;
        background-color: #fff;
    }
    .table th,
    .table td {
        padding: 5px;
        vertical-align: top;
        border-top: 1px solid #000;
        text-align: center;
    }
    .table thead th {
        vertical-align: bottom;
        border-bottom: 2px solid #000;
    }
    .table tbody + tbody {
        border-top: 2px solid #000;
    }
    .table .table {
        background-color: #fff;
    }
    .list-group {
        display: block;
        width: 100%;
        list-style: none;
        margin-top: 15px;
        margin-bottom: 15px;
    }
    .list-group p {
        width: 100%;
        height: 20px;
        line-height: 20px;
        list-style: none;
        font-size: 1.1em;
    }
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <center>
                    <h4>Sistema de Facturación DEBS</h4>
                    <h3>Reporte de Facturas<br><small>Período: {{f1 | date:"d/m/Y"}} - {{f2 | date:"d/m/Y"}}</small></h3>
                </center>
            </div>

            <table class="table">
                <thead>
                    <tr>
                        <th>No. Factura</th>
                        <th>Fecha</th>
                        <th>Cliente</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in enc %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.fecha | date:"d/m/Y"  }}</td>
                        <td>{{ item.cliente }}</td>
                        <td>{{ item.total_iva }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>